### PR TITLE
Badge-application #251 - fix for yammer posting url

### PR DESCRIPTION
**Pull request by BillZiss**
This fix addresses the Yammer URL bug that had pointed to a non-existent location.   The corrected URL now points to the badge earner's location in the Badge Application.

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
⚠️ 

@Bowman74 we need to renew/change the yammer token, since it is now in the GitHub history for this project.

**Comment by Bowman74** [comment]
@rockfordlhotka I'm not sure I have the correct Yammer permissions to change it, I'll keep looking. They probably just moved the cheese. Google will let me know.

**Comment by lewismiller** [comment]
Hi,

Can I be removed from this thread or from the git repo?

I haven't worked at Magenic in over a year.

Thanks!
Lewis Miller

**Comment by jwendl** [comment]
You will most likely want to go to view it on GitHub<https://github.com/Magenic/Badge-Application/pull/253#issuecomment-289552088>

And select not watching on the link above.

[cid:image001.png@01D2A705.EBF85040]


Thank you,
-Justin

**Comment by jwendl** [comment]
Bad email notifications... 

Go https://github.com/Magenic/Badge-Application/pull/253#issuecomment-289552088 and select "Unwatch" at the top and select "Not watching"

**Comment by Bowman74** [comment]
That’s tied to your GitHub account, you would have to stop following the project or change your notification settings.  Thanks!


.

**Pull request closed without merging**
